name: Use custom runner with a string

on:
  workflow_call:
    inputs:
      runner:
        default: ubuntu-latest
        type: string

jobs:
  trigger-mother-pipeline:
    runs-on: ${{ inputs.runner }}
    steps:
    - run: lsb_release -a
