name: Call reusable workflow with parameter
on:
  workflow_dispatch:

jobs:
  runner:
    uses: ./.github/workflows/reusable-workflow-runner.yaml
    with:
      runner: "['ubuntu-22.04', 'ubuntu-20.04']" 
