name: Use variable for specific environment with needs

on:
  workflow_dispatch:
  push:
    branches: [ "dev", "staging", "master" ]
  
  pull_request:
    branches: [ "dev", "staging", "master" ]

jobs:
  get-target:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.env }}
    steps:
      - id: env
        name: Determine target environment and set output variable
        run: |
          echo "env=${{ ( github.base_ref || github.ref_name ) == 'master' && 'production' || ( github.base_ref || github.ref_name ) }}" >> "$GITHUB_OUTPUT"

  access-variables:
    needs: get-target
    runs-on: ubuntu-latest
    environment: ${{ needs.get-target.outputs.environment }}
    steps:
      - name: Print variable from environment
        run: |
          echo "The value of the 'config' variable in the '${{ needs.get-target.outputs.environment }}' environment is: ${{ vars.config }}"
