name: Deploy workflow

on:
  workflow_call:
    inputs:
      environment: 
        required: true
        type: string
      cloud-provider: 
        required: true
        type: string
      region: 
        required: true
        type: string


jobs:

  gateway:

    runs-on: ubuntu-latest

    steps:
      - run: echo "deploy.sh gateway --environment ${{ inputs.environment }} --cloud-provider ${{ inputs.cloud-provider }} --region ${{ inputs.region }}"

  graphql:
    
    runs-on: ubuntu-latest

    needs: gateway
    steps:
      - run: echo "deploy.sh graphql-gateway --environment ${{ inputs.environment }} --cloud-provider ${{ inputs.cloud-provider }} --region ${{ inputs.region }}"


  sub-graph:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [ 'associate', 'checkout', 'account', 'store', 'punchout', 'customer-care', 'product', 'agreement' ]
    
    needs: graph-ql
    steps:
      - run: echo "deploy.sh graphql-{{ matrix.component }} --environment ${{ inputs.environment }} --cloud-provider ${{ inputs.cloud-provider }} --region ${{ inputs.region }}"


  spark-web:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [ 'associate', 'checkout', 'account', 'catalog', 'content' ]
    
    needs: sub-graph
    steps:
      - run: echo "deploy.sh spark-{{ matrix.component }} --environment ${{ inputs.environment }} --cloud-provider ${{ inputs.cloud-provider }} --region ${{ inputs.region }}"

