name: Global workflow

on:
  workflow_dispatch:
    inputs:
      environment:
          description: 'Environment to run tests against'
          type: choice
          options:
            - sandbox
            - sint
            - prod
          required: true
          default: 'sandbox'

jobs:

  deploy-sandbox:

    if: inputs.environment == 'sandbox'

    strategy:
      
      matrix:
      
        cloud-provider: [ 'gc', 'az' ]
        region: [ 'eu1' ]
      
        include:
          - cloud-provider: 'az'
            region: 'eu2'
    
    uses: ./.github/workflows/deploy/deploy.yaml 
    
    with:
      environment: ${{ inputs.environment }}
      cloud-provider: ${{ matrix.cloud-provider }}
      region: ${{ matrix.region }}
    secrets: inherit


  deploy-sint:

    if: inputs.environment == 'sint'

    uses: ./.github/workflows/deploy.yaml 
    
    with:
      environment: ${{ inputs.environment }}
      cloud-provider: 'az'
      region: 'eu1'
    secrets: inherit


  deploy-production:

    if: inputs.environment == 'prod'

    strategy:
            
      matrix:
      
        cloud-provider: [ 'gc', 'az' ]
        region: [ 'eu1', 'eu2' ]

        include:
          - cloud-provider: 'az'
            region: 'eu2'
          - cloud-provider: 'az'
            region: 'eu3'

    uses: ./.github/workflows/deploy.yaml 
    
    with:
      environment: ${{ inputs.environment }}
      cloud-provider: ${{ matrix.cloud-provider }}
      region: ${{ matrix.region }}
    secrets: inherit
