name: Global workflow

on:
  workflow_dispatch:
    inputs:
      environment:
          description: 'Environment to run tests against'
          type: choice
          options:
            - sandbox
            - sint
            - prod
          required: true
      testenv:
        type: environment
        required: false

jobs:

  deploy-production:

    if: inputs.environment == 'prod'

    strategy:
      
      # continue upon failures
      fail-fast: false
      
      matrix:
      
        #environment: [ 'sandbox', 'sint', 'prod' ]
        environment: [ 'sint' ]
        cloud-provider: [ 'gc', 'az' ]
        region: [ 'eu1' ]
      
        #include:
        #  - environment: 'sandbox'
        #    cloud-provider: 'az'
        #    region: 'eu2'
        #  - environment: 'prod'
        #    cloud-provider: 'az'
        #    region: 'eu2'
        #  - environment: 'prod'
        #    cloud-provider: 'az'
        #    region: 'eu3'

        #exclude:
        #  - environment: 'sint'
        #    cloud-provider: 'gc'
    
    uses: ./.github/workflows/deploy.yaml 
    
    with:
      environment: $${{ inputs.environment }}
      cloud-provider: ${{ matrix.cloud-provider }}
      region: ${{ matrix.region }}

    # secrets: inherit
