name: Store secret from key vault into variable

on: 
  workflow_dispatch:

env:
  SECRET_FROM_AKV: ''

jobs:

  get-secret-as-variable:

    runs-on: ubuntu-latest

    steps:

      #- name: Azure login
      #  uses: azure/login@v2
      #  with:
      #    client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - id: keyvault
        name: Get secret from AKV into variable
        run: |
          # SECRET_FROM_AKV=$(az keyvault secret show --name "SECRET_NAME" --vault-name "VAULT_NAME" --query "value")
          SECRET_FROM_AKV=$(echo "SECRET_NAME_FROM_VAULT_NAME")
          echo "::add-mask::${SECRET_FROM_AKV}"
          echo "SECRET_FROM_AKV=${SECRET_FROM_AKV}" >> "$GITHUB_OUTPUT"

      - name: Check that variable is not empty
        run: |
          if [[ ${{ steps.keyvault.outputs.SECRET_FROM_AKV }} ]]; then
              echo "The variable contains the secret"
          else
              echo "The variable does not contain the secret" && return 1
          fi