name: Use custom runner

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
    # the rest of the inputs here

jobs:
  trigger-mother-pipeline:
    runs-on: ${{ fromJSON(inputs.runner) }}
    steps:
    - run: lsb_release -a
